# Generated by Django 3.1.12 on 2025-06-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuari del Gimnàs'), ('trainer', 'Entrenador'), ('gerente', 'Gerente')], default='user', max_length=10),
        ),
    ]
