# Generated by Django 3.1.12 on 2025-06-10 17:54

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerExercise',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'trainer_exercise',
            },
        ),
        migrations.CreateModel(
            name='TrainerRutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('dificultat', models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], default='Fácil', max_length=10)),
                ('energia', models.IntegerField(choices=[(3, 'Bajo'), (7, 'Medio'), (10, 'Alto')], default=7)),
                ('exercises', models.ManyToManyField(related_name='rutinas', to='trainer.TrainerExercise')),
            ],
            options={
                'db_table': 'rutines',
            },
        ),
        migrations.CreateModel(
            name='HorarioRutina',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('dia_numero', models.IntegerField()),
                ('hora', models.IntegerField(choices=[(16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00')])),
                ('inscritos', djongo.models.fields.JSONField(default=list)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainerrutina')),
            ],
            options={
                'db_table': 'trainer_horariorutina',
                'unique_together': {('dia', 'hora', 'dia_numero')},
            },
        ),
    ]
